name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: |
        find ./src -name '*.csproj' -type f -exec dirname {} \; | sort -u | xargs -I {} dotnet restore {}

    - name: Build
      run: |
        find ./src -name '*.csproj' -type f -exec dotnet build --no-restore {} \;

    - name: Test
      run: |
        find ./src -name '*.csproj' -type f -exec dotnet test --no-build --verbosity normal {} \;
